name: Python package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - name: Publish Python Package
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          publish-package: true

      - name: Build wheel and source distribution
        run: |
          cd src
          pip install setuptools wheel
          python setup.py sdist bdist_wheel

      - name: Release version
        id: release_version
        run: |
          cd src
          app_version=$(cat setup.py | grep version | sed "s/version='\([0-9]\+\.[0-9]\+\.[0-9]\+\)',/\1/" | sed s/[[:space:]]//g)
          echo "app_version=$app_version" >> $GITHUB_ENV
          echo "app_version=$app_version"

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: src/dist/*.whl
          tag: v${{env.app_version}}
          release_name: v${{env.app_version}}
          overwrite: true
          file_glob: true
          body: ${{github.event.commits[0].message}}
